### PR TITLE
Add deinterlace recipe

### PR DESCRIPTION
**Pull request by kfrn**
Before
interlaced_video

and after
deint_video

### CODE REVIEW

**Comment by ablwr** [comment]
WHHHOOOAAAAAA

**Comment by retokromer** [comment]
Thank you very much indeed!

**Comment by ablwr** [comment]
I'd be interested in seeing those two images integrated into the display of the script, like a couple of the filters now have.

**Comment by retokromer** [comment]
This was the 100<sup>th</sup> pull request!

**Comment by ablwr** [comment]
We must celebrate!

**Comment by kieranjol** [comment]
Brilliant!! And those images are great.

**Comment by kfrn** [comment]
Shall I embed the images, then?

**Comment by ablwr** [comment]
I would like this!

**Comment by ghost** [comment]
`format=pix_fmts=yuv420p` can be shortened to `format=yuv420p`, and `yadif=1` often looks better than the default mode `0` depending on your content. Note that mode `1` will double the output frame rate which is expected because it will output one frame for each field. Also, there are other deinterlacers available to try such as [bwdif](https://ffmpeg.org/ffmpeg-filters.html#bwdif) and [w3fdif](https://ffmpeg.org/ffmpeg-filters.html#w3fdif).

**Comment by kfrn** [comment]
Thank you @llogan. I went to the ffmpeg docs for that ([here](https://www.ffmpeg.org/ffmpeg-all.html#Examples-89)), so thanks for letting me know about the shorter version.
Perhaps I should add a note about the different options for `yadif`.
There was some talk in #141 about comparing different deinterlacers. Here I just went with `yadif` since it seems widely used, and I liked the results.

**Comment by retokromer** [comment]
Yes, @kfrn, you could possibly add the note. And then I’ll make a new release.

I will also try to have my students testing the current FFmpeg’s implementation of the de-interlacing filters next week, when I‘ll be teaching at the Bern University of Applied Sciences. That’s an interesting exercise for them, which could provide useful information to `ffmprovisr` as well!

**Comment by kfrn** [comment]
Is it okay if I do this in the next few days? I also wanted to add one or two new recipes, but they're not finished yet.
And very cool, @retokromer ! Please do report back. :)

**Pull request merged**
