### PR TITLE
updates contributors list

### PR DESCRIPTION
**Pull request by ablwr**

### CODE REVIEW

**Comment by retokromer** [comment]
This modifies (at least on my laptop) the list in a continuous text. I would add commas after each item if it is represented in a continuous text.

**Comment by retokromer** [comment]
Sorry, I closed by mistake…

**Comment by ablwr** [comment]
MARKDOWN STRIKES.

**Review by retokromer — APPROVED** [review]

**Comment by retokromer** [comment]
Markdown is not my friend.

**Pull request merged**
