### PR TITLE
Moves CSS around, fixes overflow error on small devices

### PR DESCRIPTION
**Pull request by ablwr**
moves visual style to "local" css (shows how little of bootstrap we are using for style), simplifies button style to one class, breaks words on small screens

### CODE REVIEW

**Comment by kfrn** [comment]
LGTM! Out of curiosity: why are the explicit inherits for `button` necessary?

**Comment by ablwr** [comment]
They are necessary because other parts of bootstrap wants to overwrite them, I think. If I manage to ditch the bootstrap css, I can ditch this extra code too. It took a while to figure out this is what was causing the problem!

**Comment by kfrn** [comment]
Right, gotcha! I've used Bootstrap, but not extensively. At work we're using a newish framework called Bulma, which is very nice so far.

**Comment by ablwr** [comment]
There's nothing wrong with it although people like to give it shit, I am just obsessed with minimizing dependencies and removing all the stuff we don't use or need LIKE A BIG NERD

**Pull request merged**
