### PR TITLE
Changes h3 to h5

### PR DESCRIPTION
**Pull request by Anushka-codergirl**
Work done!

### CODE REVIEW

**Comment by ablwr** [comment]
Hi @Anushka-codergirl! Thanks for making a PR :)

@retokromer would this help your script?

I do think it makes sense for headings that are initially hidden to be a lower-level heading. In general, I think the whole page could use a semantic review, as @kfrn suggests in #397.

But I am in support of incremental changes in the right direction!

**Review by ablwr — APPROVED** [review]

**Comment by kfrn** [comment]
Thanks for this, Anushka! However, we're looking to make our HTML more semantic, so I don't think this quite works, because now the heading levels are out of step - `h1`, `h2`, then `h5`. So I'd probably keep these as `h3`s.

**Comment by kfrn** [comment]
Oops, I hadn't refreshed the page and seen @ablwr's comment or the merge. Nevermind, then!

**Comment by retokromer** [comment]
@ablwr Not really, I guess, but I’ll update it.

**Pull request merged**
