### PR TITLE
swapped out intro-leads for h3

### PR DESCRIPTION
**Pull request by todrobbins**
Before:

Screen Shot 2020-06-02 at 6 16 03 PM

After:

Screen Shot 2020-06-02 at 6 16 13 PM

### CODE REVIEW

**Review by kfrn — COMMENTED** [review]
Thank you, Tod! Love the screenshots 

Heh, so this is an existing problem that we were talking about just before (https://github.com/amiaopensource/ffmprovisr/issues/429#issuecomment-637864141), but in terms of semantic HTML, these should really be headers rather than `span`s. (Logically, H3s).

@todrobbins, would you be willing to change the `intro-leads` to H3s and see how that looks?

**Comment by todrobbins** [comment]
Ha! I was thinking the same thing actually. Will do!

**Comment by kieranjol** [comment]
Love the "after" screenshot, so much clearer.

**Comment by todrobbins** [comment]
@kfrn ✅ done

Screen Shot 2020-06-03 at 9 31 14 AM

**Review by kfrn — APPROVED** [review]
LGTM! Are we still using the `intro-lead` CSS class at all? If not, feel free to delete ie.

**Comment by todrobbins** [comment]
Good catch!

✅ Removed!

**Comment by ablwr** [comment]
Nice work!

**Review by kfrn — APPROVED** [review]
Thanks, @todrobbins!

**Pull request merged**
