### PR TITLE
add ffmpeg-artschool as sibling

### PR DESCRIPTION
**Pull request by ablwr**
Connected to https://github.com/amiaopensource/ffmprovisr/issues/447

## Checklist

* [X] I've referred to the [Guidelines for contributing](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/readme.md#guidelines-for-contributing)

### CODE REVIEW

**Review by kieranjol — COMMENTED** [review]
I'm not a web-dev so I don't know the significance of this, but this seems to be the only sibling that doesn't have the `target=_blank"` attribute, was that intentional?

**Comment by ablwr** [comment]
No that was just me typing it and not looking at the other lines :joy: .. I'll fix it

**Comment by bturkus** [comment]
once you go artschool there's no going back

**Comment by ablwr** [comment]
that's right @bturkus !!!

but also I fixed it, sorry for being so LAZY all the time

**Review by kieranjol — APPROVED** [review]
Can't wait to try this out so that I can alleviate the FOMO I felt at the time!

**Comment by ablwr** [comment]
Me too! Amazing project @bturkus and everyone else that I am again, too lazy to tag in this because their names don't come up in the autocomplete!

**Comment by kfrn** [comment]
Yeah, I can't wait to give this a whirl! Very neat stuff

**Pull request merged**
