### PR TITLE
Adds a filter section

### PR DESCRIPTION
**Pull request by ablwr**
Thanks @privatezero for some scripts! This expands ffmprovisr a little bit to include some players from the `ffprobe` and `ffplay` families.

### CODE REVIEW

**Comment by kieranjol** [comment]
All looks good to me, great additions!

**Comment by ablwr** [comment]
I'm sure I made mistakes or could be clearer... but I'm also sure Reto will find them!

**Comment by retokromer** [comment]
Sorry, I cannot go into it now, therefore I merge – and will check later.

**Comment by retokromer** [comment]
@ablwr I checked and changed a little in this [PR](https://github.com/amiaopensource/ffmprovisr/pull/125), because `-filter:v` doesn’t exist in `ffplay`.

**Pull request merged**
