### PR TITLE
add cross ref to QCTools doc

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by ablwr** [comment]
Best at the bottom or up top before the explanation?

**Comment by retokromer** [comment]
I don’t think before the explanation, but perhaps just after it, instead as of a «footnote».

**Comment by ablwr** [comment]
Before the breakdown of each part of the command, I mean? This breakdown will get very lengthy when the signalstats part gets parsed.

**Comment by ablwr** [comment]
I think it'd be best as a new <p> immediately under "This will create an XML report for use in QCTools for a video file with one video track and one audio track."

But also don't care that much so do as you think is best!

**Comment by retokromer** [comment]
Moved.

**Pull request merged**
