### PR TITLE
check if connected to the web

### PR DESCRIPTION
**Pull request by retokromer**
Use the online version when the computer is connected to the Web, and the local version otherwise.

### CODE REVIEW

**Comment by ablwr** [comment]
coooooooooooool

**Comment by retokromer** [comment]
Or possibly even:
```bash
if [[ "$(uname -s)" = "Darwin" ]] ; then
    default_browser=$(plutil -convert json ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist -r -o - | grep https -b1 | tail -n1 | cut -d'"' -f4)
    if ping -c 1 amiaopensource.github.io >/dev/null 2>&1 ; then
        ffmprovisr_path='https://amiaopensource.github.io/ffmprovisr/'
    else
        ffmprovisr_path=$(find /usr/local/Cellar/ffmprovisr -iname 'index.html' | sort -M | tail -n1)
    fi
    if [ -n "${default_browser}" ] ; then
        open -b "${default_browser}" "${ffmprovisr_path}"
    else
        open "${ffmprovisr_path}"
    fi
elif [[ "$(uname -s)" = "Linux" ]] ; then
    if ping -c 1 amiaopensource.github.io >/dev/null 2>&1 ; then
        ffmprovisr_path='https://amiaopensource.github.io/ffmprovisr/'
    else
        ffmprovisr_path=$(find ~/.linuxbrew/Cellar/ffmprovisr -iname 'index.html' | sort -M | tail -n1)
    fi
    xdg-open "${ffmprovisr_path}"
fi
```
because: if the function `ffmprovisr` responds, then the resource is installed anyway.

**Comment by kieranjol** [comment]
I haven't tried this but it's such a brilliant idea - thanks Reto!

**Review by privatezero — APPROVED** [review]
Super cool!!

**Pull request merged**
