### PR TITLE
no apologies

### PR DESCRIPTION
**Pull request by dericed**
check on https://github.com/amiaopensource/ffmprovisr/pull/181#issuecomment-299276451

### CODE REVIEW

**Comment by ablwr** [comment]
@privatezero please delete your apology

**Comment by privatezero** [comment]
eeek! I'm sorry @ablwr! Will revise!

**Comment by retokromer** [comment]
Are 6148 bytes enough for «long-term annoyance»?
(ref. https://twitter.com/dericed/status/788735501108928512)

**Comment by ablwr** [comment]
Sorry, no.

**Pull request closed without merging**
