### PR TITLE
update maintainers

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by kfrn** [comment]
Sorry to see you go, @retokromer! May I ask why?

**Comment by retokromer** [comment]
For health reasons.

**Comment by kieranjol** [comment]
:(
I'm sorry to hear this Reto. I'd hope that you would stay on the list, I
send you my best.

**Comment by retokromer** [comment]
As long as I have the energy I’ll continue to contribute, that’s for sure, but I prefer to pas the responsibility to others.

**Comment by privatezero** [comment]
All the best wishes for your health @retokromer

**Comment by JonnyTech** [comment]
Why remove yourself completely @retokromer rather than move to the contributors section? Hoping you recover to wellness quickly.

**Comment by retokromer** [comment]
@JonnyTech It’s from the [maintainers’ list](https://github.com/amiaopensource/ffmprovisr/commit/0d12f57720eafd125825939e7b2c26fa0140f642) only, while the contributors’ list is generated from time to time by @ablwr using octohatrack.

**Comment by ablwr** [comment]
Wishing you all the beset @retokromer and sorry to see you go! Thanks for your endless dedication to making ffmprovisr better.

**Pull request merged**
