### PR TITLE
changes buttons into div-rows

### PR DESCRIPTION
**Pull request by ablwr**
Like this?

screen shot 2017-10-17 at 21 00 40

screen shot 2017-10-17 at 21 02 27

Restructured, got rid of tooltips, lengthened recipe names if necessary, got rid of <span> wrapping buttons, replaced buttons with divs, renamed btn class to recipe, added green hover effect, made VHS/comet grow in a better way.

### CODE REVIEW

**Comment by retokromer** [comment]
Is the colour of the text in the green fields #000000? (Just asking, because the contrast between background and text seems to me to be lower.)

**Comment by ablwr** [comment]
Hmm... using "named" colors of white and black (except for the green).

**Comment by ablwr** [comment]
I boosted the size slightly and switched to the sans-serif font, maybe that is causing the difference?

**Comment by retokromer** [comment]
It’s a matter of contrast: green to black is less than dark grey to white. I just noticed it, and this may make reading more difficult for view impaired people. Yet this is not blocking. (I don’t think that a lighter green would be nice.)

**Comment by ablwr** [comment]
No, contrast is important. I thought you meant it looked different from before. I'll take a look at it and refine so we get better visibility/contrast (although not tonight, but tomorrow).

**Review by retokromer — APPROVED** [review]
Otherwise, LGTM.

**Comment by ablwr** [comment]
I'll work on contrast in a new branch!

**Pull request merged**
