### PR TITLE
Embed links; remove extra line about comma

### PR DESCRIPTION
**Pull request by kfrn**
A small tidy-up.
I haven't got the OCR ones working yet, but these scripts are mega cool! Thanks for adding them.

### CODE REVIEW

**Comment by ablwr** [comment]
Oh, the OCR ones as I found out on twitter from @privatezero need to be installed `--with-tesseract`! I forgot to make a note to add that.

**Comment by kfrn** [comment]
Ah, thanks! I think it would be great if you or @privatezero added that in. :)

**Comment by ablwr** [comment]
I'll add it!

**Comment by retokromer** [comment]
Thank you, @kfrn! It’s indeed more readable.

**Comment by retokromer** [comment]
We use it for intertitles – also when written in [Fraktur](https://en.wikipedia.org/wiki/Fraktur) – and subtitle extraction. It works well!

**Pull request merged**
