### PR TITLE
add view format info

### PR DESCRIPTION
**Pull request by kieranjol**
Hi,

I'm not sure about the formatting of the `dd` tags for the example list. In general, as this was a little different to other recipes, I wasn't sure how to describe all this, so feedback will be very welcome.

### CODE REVIEW

**Comment by ablwr** [comment]
I think this looks good! Thanks for adding this thing!

**Comment by retokromer** [comment]
It’s syntactically possible, but it’s better to use either:
`<dd>…<br/>…</dd>`
or:
`<dd><p>…</p><p>…</p></dd>`

**Comment by retokromer** [comment]
In this case, I would suggest:

```
<dd>Tells ffmpeg which kind of option you want, for example:
  <ul>
    <li><code>encoder=libx264</code></li>
    <li><code>decoder=mp3</code></li>
    …
  </ul>
</dd>
```

i.e. in one `<dd>` structure, but your list as `<ul>` after the introduction.

**Comment by kieranjol** [comment]
Eek, I thought I replied yesterday via email. That all sounds good, Reto. Will alter now.

**Comment by retokromer** [comment]
Closes https://github.com/amiaopensource/ffmprovisr/issues/93. Thank you!

**Pull request merged**
