### PR TITLE
rebrand "sister" to gender-neutral "sibling"

### PR DESCRIPTION
**Pull request by ablwr**
## Checklist

* [X] I've referred to the [Guidelines for contributing](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/readme.md#guidelines-for-contributing)

### CODE REVIEW

**Review by kieranjol — APPROVED** [review]
+100

**Comment by ablwr** [comment]
ty ty for the quick pr!
8e39f744fd55b321

**Comment by kieranjol** [comment]
Perfect cat, made my day <3

**Comment by kfrn** [comment]
> ty ty for the quick pr!
> 8e39f744fd55b321

Oh so sweet!

And thanks for the code change too :)

**Pull request merged**
