### PR TITLE
Add entry on stream mapping

### PR DESCRIPTION
**Pull request by kfrn**
I thought it'd be a nice addition to the **Advanced topics** section. 

Feedback welcomed!

### CODE REVIEW

**Review by retokromer — APPROVED** [review]
LGTM

**Comment by kieranjol** [comment]
LGTM

**Review by ablwr — APPROVED** [review]

**Comment by retokromer** [comment]
Thank you again, @kfrn, you rock!

**Comment by ablwr** [comment]
Katherine is seriously THE BEST!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by kfrn** [comment]
You folks are too kind! :blush:

**Pull request merged**
