### PR TITLE
split audio/video tracks - match command line with explanation

### PR DESCRIPTION
**Pull request by kieranjol**
explanation said `0:v:0`, command line said `0:v`

I know that I could probably just commit this as is, but I figure it's best to make a PR.

### CODE REVIEW

**Review by ablwr — APPROVED** [review]

**Comment by ablwr** [comment]
You're up late!

**Comment by kieranjol** [comment]
Merging before sleep :sleepy: :sleeping_bed:

**Comment by kieranjol** [comment]
Thanks for reviewing!

**Comment by kfrn** [comment]
Digging github's interpretation of your commit message!

> explanation said `0✌️0`, command line said `0:v`

**Pull request merged**
