### PR TITLE
index: various edits

### PR DESCRIPTION
**Pull request by ghost**
Create GIF: Add examples using the palettegen and paletteuse filters.

WAV to MP3: Mention what happens if "-ar" is omitted.

Batch Processing: Add "-map 0" to map all streams (from input 0)
instead of relying on stream selection defaults.

Split audio and video tracks: Use stream specifiers instead of indexes.
More efficient and less prone to errors.

Transcode to H.264: Default is not 4:2:2, but depends on input.

NTSC to H.264: Do all filtering in one filtergraph for better control.
Use format instead of "-pix_fmt" when filtering.

Various: Replace "-c:v copy -c:a copy" with "-c copy" and other minor
edits. Remove superfluous "-f image2" instances.

### CODE REVIEW

**Comment by ablwr** [comment]
This... is... amazing!!!

**Comment by ablwr** [comment]
Tested and approved. So great to have some ffmpeg-contributor expertise knowledge dropped into this.

**Comment by retokromer** [comment]
Thanks a lot @llogan for the very useful adds and corrections!

**Comment by ghost** [comment]
Glad to help. I'll try to add more sometime.

**Pull request merged**
