### PR TITLE
Making links alive

### PR DESCRIPTION
**Pull request by retokromer**
This is a test. Sorry, I cannot check now if it works.

### CODE REVIEW

**Comment by kieranjol** [comment]
It's duplicating the URL, so locally it's producing:
`file:///C:/Users/kieran.oleary/Desktop/ffmprovisr-retokromer-patch-1/%22file:///C:/Users/kieran.oleary/Desktop/ffmprovisr-retokromer-patch-1/index.html#one_thumbnail"`

and online it's producing:
`https://raw.githubusercontent.com/amiaopensource/ffmprovisr/retokromer-patch-1/%22https://htmlpreview.github.io/?https://github.com/amiaopensource/ffmprovisr/blob/retokromer-patch-1/index.html#to_prores"`

Edit: It's like it's prepending the parent location?

**Comment by retokromer** [comment]
I presume it doesn’t like the `&` sign.
If without `&quot;` should work fine, then probably `\"` could be a solution for having both a working code and a correct HTML5.

**Comment by kieranjol** [comment]
The latest commit produces working links for me anyhow, great stuff. I can't comment on the actual code though.

**Comment by retokromer** [comment]
Thank you!

**Comment by kieranjol** [comment]
👍 👍

**Comment by ablwr** [comment]
What a treat to wake up to solved work and collaborative problem-solving!!! You two are the best. Apologies for snoozing away!

**Pull request merged**
