### PR TITLE
update Transcode to ProRes

### PR DESCRIPTION
**Pull request by retokromer**
This should resolve (at least part of) https://github.com/amiaopensource/ffmprovisr/issues/72.

### CODE REVIEW

**Comment by todrobbins** [comment]
Looks good! Thanks @retokromer!

**Comment by richardpl** [comment]
The prores_aw, current "prores" encoder is going to be removed.d

**Comment by kieranjol** [comment]
Is it going to be removed completely, or will kostya's encoder be made the
default instead? That's what I picked up from your patch on ffmpeg-devel.

**Comment by retokromer** [comment]
Thank you, @richardpl! We will certainly update our information as soon as a new release of FFmpeg that includes the change will be published.

For the moment, one problem I see is the big difference regarding the executing time.

**Comment by richardpl** [comment]
Well that only applies for default parameters. Try with -qscale:v 4 for prores_ks.
With default parameters prores_ks try very hard to match bitrate.

**Comment by retokromer** [comment]
@richardpl: I cannot find a transparent documentation about the exact effect of the `-qscale` parameter, but I notice «strange» behaviours when applied to the resonance test patterns I usually use to check the encoding quality. Do you have a reference where this is documented? Otherwise I will delve into the code and do the reverse-engineering, as soon as I will have the time to do so.

(I almost never use the default parameters, but I do measure a considerable difference in executing time between `prores` and `prores_ks`.)

**Comment by richardpl** [comment]
It is documented in source code. Let me cite original author:
"The answer is that the encoder tries to find the best quantiser for each slice where best = gives the least error and uses about the allocated number of bits. I used simple linear search and IIRC didn't implement good handling for the (relatively) low bitrates because it worked GoodEnough(TM). Though some people said it actually followed bitrate "better" (i.e. with less variation)."

**Comment by retokromer** [comment]
Thank you, @richardpl!

I actually would like to know more regarding what happens exactly when switching e.g. from 4 to 5. I also noticed that in the different web documents, there are some «fluctuations» 0–10 (10 best), 1–32 (1 best) or 0–32 (0 best). My guess is that the interval depends on the bit-depth (BTW: we would also need 12, therefore yuva444p10le seem not a good choice to me, and 16 for alpha). I will check the code.

**Comment by richardpl** [comment]
16 for alpha is by default. 12bit is snake oil until someone provides actual 12 bit sample.

**Comment by retokromer** [comment]
Oh, I can provide 4444 with 12 bit as soon as I am back in the lab.

**Comment by retokromer** [comment]
@richardpl Please give me an [email address](https://reto.ch/cgi-bin/feedback.pl) where I can sent you the link to the files.

**Pull request merged**
