### PR TITLE
Create more subheadings and reorganise commands

### PR DESCRIPTION
**Pull request by kfrn**
I was thinking about the page's navigability, and considered that the conceptual grouping could be tighter - and also that there were quite a few things under the **Other** heading. So, I decided to create some more page headings and regroup certain commands. This also leaves fewer items in the miscellaneous category.  I also made a (rudimentary) "table of contents" at the top of the page.

What do you all think???? On the right track or not  at all?

I was thinking about some of the comments in #235, such as @retokromer's [feedback](https://github.com/amiaopensource/ffmprovisr/issues/235#issuecomment-333914347).  
But, I just realised that I may have jumped the gun on the redesign @ablwr - I hope you don't mind! Let's consider this the starting point only.

### CODE REVIEW

**Comment by kfrn** [comment]
New groupings:
-------

**Change container (rewrap)**
- MKV to MP4

**Change codec (transcode)**
- Transcode to ProRes  
- Transcode to H.264  
- H.264 from DCP 
- Create FFV1.mkv  
- Images to GIF  
- Convert DVD to H.264 
- Transcode to H.265/HEVC
- WAV to MP3  
- WAV to AAC/MP4

**Change video properties** (RENAMED from **Change formats**, which I think is not a very descriptive name)
- 4:3 to 16:9  
- 16:9 to 4:3  
- SD to HD  
- Change Display Aspect Ratio
- Convert colourspace

**Join, trim, or excerpt a video** (NEW)
- Join files together  
- Split file into segments  
- Trim video 
- Excerpt from beginning  
- Excerpt to end 
- Excerpt from end

**Work with interlaced video** (NEW)
- NTSC to H.264  
- Deinterlace video  
- Inverse telecine 
- Set field order  
- Check interlacement

**Use filters or scopes** (RENAMED from **Filters**)
- Audio Bitscope  
- Graphic for audio  
- Broadcast Range  
- Vectorscope 
- Side by Side Videos/Temporal Difference Filter

**View or strip metadata** (NEW)
- Pull specs  
- Strip metadata

**Generate image files from a video** (NEW)
- Create GIF  
- One thumbnail  
- Many thumbnails

**Create a video** (NEW)
- Image sequence into video  
- Create video from image and audio

**Overlay timecode or text** (NEW)
- Text Watermark  
- Overlay image watermark on video  
- Burn in timecode

**Normalize/Equalize Audio**
- Flip phase shift  
- Calculate Loudness Levels  
- RIAA Equalization 
- One Pass Loudness Normalization  
- Two Pass Loudness Normalization

**Preservation tasks**
- Batch processing (Mac/Linux)  
- Batch processing (Windows) 
- Create MD5 checksums (video frames)  
- Create MD5 checksums (audio samples) 
- QCTools report (with audio)  
- QCTools report (no audio) 
- Check FFV1 fixity  
- Read/Extract EIA-608 Closed Captioning

**Generate test files**
- Mandelbrot  
- SMPTE bars  
- Test pattern  
- Play HD SMPTE bars 
- Play VGA SMPTE bars  
- Sine wave  
- SMPTE bars + Sine wave audio 
- Broken file

**Repair**
- Fix AV Sync: Resample audio

**Use OCR** (NEW)
- Show OCR  
- Export OCR

**Other**
- Play an image sequence  
- Split audio and video tracks  
- Extract audio 
- Combine audio tracks  
- Create access MP3 (+ access MP3 with copyright notice) 
- Flip video image  
- Modify speed  
- Set stream properties 
- Create ISO  
- Compare Video Fingerprints  
- Generate Video Fingerprint 
- CSV with timecodes and YDIF 

------

DELETED heading: **Make derivative variations** (commands subsumed into**Join, trim, or excerpt a video**, **Generate image files from a video**, and **Other**)

**Comment by kfrn** [comment]
Also, I don't know how several older commits snuck into this PR! It should be just the last three:
- Reorganise ffmpeg commands under more/different subheadings `da94557`
- Command name change: 'View Format Info' to 'View ffmpeg subprogram info' `efd9e55`
- Add 'contents' section at the top of the page `fd7528a`  

It's just these ones that need review.  
Sorry about this! I started with a clean and up to date master, or at least I thought I did ... :disappointed: :-1:

**Comment by retokromer** [comment]
Nit: A `</div>` is missing at the end.

**Comment by kfrn** [comment]
@retokromer fixed! I also removed a stray comment I left within.

**Comment by retokromer** [comment]
@kfrn: I’ll check as soon as possible.

**Comment by kieranjol** [comment]
This is wonderful!!! I love the new tape icons. Extraordinary work!!!

* Could `Create a video` be made more specific to `Create a video from images`?
* Could `set stream properties` be moved to the `change video properties section`?
* The final recipe, `view ffmpeg subprogram information` does not contain information it looks like.
* I think some of the items in 'Other' could be moved into a relevant section, but we can move that stuff around after this is merged.

**Comment by ablwr** [comment]
Oh this is great!!!

**Comment by ablwr** [comment]
@kfrn really this is so fantastic, thank you for doing this work! It's amazing to see how big ffmprovisr has gotten, I think we had just been adding scripts and didn't realize how much this structural organizational work needed to happen, so thank you thank you.

**Comment by ablwr** [comment]
@kieranjol already noted that something is up with the very last script/button. I also agree we can do some more moving around and renaming after this one is merged.

**Review by retokromer — APPROVED** [review]

**Comment by kieranjol** [comment]
Aye,all my suggestions should not hold up a merge.

**Comment by kfrn** [comment]
Yay, thanks so much for the positive feedback, folks!

I've made the changes suggested by @kieranjol. Ooops on that last recipe - I had changed the ID, but not the other matching tag. 

I definitely agree with @kieranjol that this needs further refinement: finding categories for more of the Misc items, refining the new and existing categories (good naming is hard!), and possibly moving some existing recipes (e.g.: should _Images to GIF_ be under **Change codec** ?) So I hope others will take up the baton now! :sunglasses:

**Review by retokromer — APPROVED** [review]

**Comment by kieranjol** [comment]
Thanks Katherine! All looks lovely.

**Review by kieranjol — APPROVED** [review]

**Review by ablwr — APPROVED** [review]

**Pull request merged**
