### PR TITLE
changed italics and bold

### PR DESCRIPTION
**Pull request by mgiraldo**
to use proper semantic tags 🧐

### CODE REVIEW

**Comment by kfrn** [comment]
Nice catch! However, IIRC, we've talked about `<i>` v. `<em>` (etc) before and decided to stick with the current usage. Let me try to find the discussion. **Edit**: hmm, I may have imagined this/be thinking of a different project. Does anyone else remember talking about this topic?

**Comment by retokromer** [comment]
Indeed, we discussed that at the beginning, at the AMIA hackday. We did consider that the good old typographic way was shorter, still having the same clarity.

**Comment by ablwr** [comment]
I'm inclined to accept these changes though because it's better moving forward into the HTML future?

**Comment by retokromer** [comment]
Just to be clear:

- I’m no longer a maintainer;
- I’ve just given the background I remember;
- I don’t have a strong opinion on this «issue».

**Comment by kfrn** [comment]
I say ship it! 🙂 Once the conflict is resolved. @mgiraldo, let us know if you'll do that or if you prefer to hand off the merge conflict resolution.

**Comment by mgiraldo** [comment]
maybe hand off?

- mga

**Comment by kfrn** [comment]
Cool, I'll sort that out!

**Comment by mgiraldo** [comment]
thanks!

**Comment by ablwr** [comment]
mga so lazy

**Comment by kfrn** [comment]
Done! (Actually was a simple one). 

Thanks  @mgiraldo !

**Comment by kfrn** [comment]
Lol Ashley ya rascal!

**Comment by ablwr** [comment]
Hahaha thank you @kfrn!!!

**Comment by ablwr** [comment]
and thank you @mgiraldo !!!!!!! 👾

**Pull request merged**
