### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by kfrn**
I sneaked in a couple of other link changes before, @retokromer

### CODE REVIEW

**Comment by retokromer** [comment]
Two remarks:

- Is the `index.html` part not requested?
- Can we avoid the full link as you did previously? (This way it works off-line as well.)

**Comment by retokromer** [comment]
I don’t know if `index.html` or `./index.html` is better.
@kieranjol : Is there any Windows issue?

**Comment by kfrn** [comment]
Ah bugger. I just grabbed them from the browser address. Now fixed - sorry!

**Comment by retokromer** [comment]
Thank you! I guess we can merge.

**Comment by retokromer** [comment]
@kfrn: It works fine now on different browsers, except one. Therefore it’s actually the browser and not the code. Thank you again!

**Comment by kfrn** [comment]
I'm on my Windows computer. Working offline, either seem to work - but only when opening in a new tab. Neither go to the linked recipe just from clicking.

**Comment by retokromer** [comment]
Thank you for the feedback! I just made a release, and will test it on my Intel NUC test machine under Windows (for the training in Bangkok).

**Pull request merged**
